# Generated by Django 3.2.6 on 2022-05-17 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('doc', models.FileField(upload_to='files')),
            ],
        ),
    ]
