# Generated by Django 3.2.6 on 2022-05-18 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='temp_id',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='upload',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
